name: Build and Create Release for pymusic

on:
  push:
    paths:
      - src/**
  workflow_dispatch:

jobs:
  build_and_release_windows:
    runs-on: windows-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install Dependencies
      run: | 
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Install UPX
      uses: crazy-max/ghaction-upx@v3
      with:
        install-only: true

    - name: Build pymusic
      run: pyinstaller src/pymusic.spec --distpath dist --workpath build

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: pymusic_windows
        path: dist/pymusic.exe

    - id: get_version
      run: |
        $version = (& dist/pymusic --version) -replace '^pymusic\s+', 'v'
        echo "version=$version" >> $env:GITHUB_OUTPUT

    - id: get_body
      run: |
        $lines = Get-Content CHANGELOG.md
        $firstMatch = $lines | Where-Object { $_ -match '^##\s+\d+\.\d+\.\d+' } | Select-Object -First 1
        $start = $lines.IndexOf($firstMatch)

        $rest = $lines[($start + 1)..($lines.Count - 1)]
        $nextMatch = $rest | Where-Object { $_ -match '^##\s+\d+\.\d+\.\d+' } | Select-Object -First 1
        $end = if ($nextMatch) { $lines.IndexOf($nextMatch) - 1 } else { $lines.Count - 1 }

        $latest = $lines[$start..$end]
        $text = $latest -join "`n"

        echo "body<<EOF" >> $env:GITHUB_OUTPUT
        echo "$text" >> $env:GITHUB_OUTPUT
        echo "EOF" >> $env:GITHUB_OUTPUT

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get_version.outputs.version }}
        release_name: ${{ steps.get_version.outputs.version }}
        body: | 
          ${{ steps.get_body.outputs.body }}

    - name: Upload to Release
      uses: svenstaro/upload-release-action@v2
      with:
        file: dist/pymusic.exe
        tag: ${{ steps.get_version.outputs.version }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}

  build_and_release_linux:
    runs-on: ubuntu-latest
    needs: build_and_release_windows

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build pymusic
        run: pyinstaller src/pymusic.spec --distpath dist --workpath build

      - uses: actions/upload-artifact@v4
        with:
          name: pymusic_linux
          path: dist/pymusic

      - name: Upload to Release
        uses: svenstaro/upload-release-action@v2
        with:
          file: dist/pymusic
          tag: ${{ needs.build_and_release_windows.outputs.version }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}